name: CI

on: [push, pull_request]
  
jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with: 
          toolchain: stable
          components: rustfmt, clippy 

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install Dependencies
        run: cargo fetch

      - name: Check Formatting
        run: cargo fmt --verbose -- --check

      - name: Run Linter
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build Project
        run: cargo build --all-targets --all-features

      - name: Run Tests
        run: cargo test --all-targets --all-features