name: Release

on: 
  push: 
    tags:      
      - v[0-9]+.[0-9]+.[0-9]+


jobs: 

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - uses: dtolnay/rust-toolchain@stable
        with: 
          toolchain: stable
          components: rustfmt, clippy 
      
      - name: Build
        run: cargo build --verbose
      
      - name: Test
        run: cargo test --verbose 

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Generate release note
        run: "bash create-release-note.bash ${{ env.TAG_NAME }}"
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.JF_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          bodyFile: "release-note.md"
      
